### ISSUE TITLE
Move working_files directory over during movedata workflow

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#131]
In MoveData-workflow.cwl, we need to add steps that copy the working_files directory that we create to the other three servers. This will be similar to the steps dataTransfer-scaffold-2gmodProd, dataTransfer-scaffold-2gmodStage, dataTransfer-scaffold-2apollo

**Comment by ZhiXuanLai** [comment]
Hi @mpoelchau. Taking saceub as an example, I am wondering if `working_files/saceub/SEUB3.0` is the directory we want to copy to the other three servers. Thank you!

**Comment by mpoelchau** [comment]
@ZhiXuanLai yes, that's it. First you'll need to make the directory on the destination server, though (similar to `files_4_Apollo2Server/MoveData/createFolder.cwl`). 
Then you can set up something along the lines of: 

```
baseCommand: [rsync]
arguments:
  - prefix: -rlvP
    position: 1
    valueFrom: $(inputs.PATH[1])/$(inputs.tree[0])/$(inputs.tree[1])/
  - position: 2
    valueFrom: $(inputs.Gmod_account):$(inputs.PATH[1])/$(inputs.tree[0])/$(inputs.tree[1])/
```
