### ISSUE TITLE
add functional annotation directory to create-symlink.cwl 

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#133]
Most of our new organisms should now have functional annotations. We need to incorporate them into the create-symlink.cwl workflow, based on the functional annotation directory name. I think the steps to add this should look something like this: 

- Add functional annotation directory name to yml file; perhaps to the tree input? 
- It would be great if this step could be conditional - perhaps based on whether the functional annotation directory name is NA or not? 
- I suspect the command inside the workflow will look something like this:
- 
```
baseCommand: [ln]
arguments:
  - prefix: -s
    position: 1
    valueFrom: $(inputs.PATH[0])/$(inputs.tree[0])/$(inputs.tree[1])/$(inputs.deepPATH_genomic_fasta[0])/$(inputs.deepPATH_analyses[0])/[functional-annotation-directory-name]/
    #target directory
  - position: 5
    valueFrom: $(inputs.MAIN_PATH)/$(inputs.tree[0])-($(inputs.scientific_name[0])_$(inputs.scientific_name[1]))/$(inputs.tree[1])/2.Official or Primary Gene Set/.
```
