### ISSUE TITLE
Workflow4: wget ->gunzip

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#16]
Link: https://github.com/NAL-i5K/CWL_Common-Workflow-Language/tree/dev/demo_workflow4

**demo_workflow3** successful connect two blocks, but just allow one input url.
**demo_workflow4** want to use all *type: File[]*

There are two ways to expand the function to multiple 
- take File[], but I do not know how to parse each element out by InlineJavascriptexpression
- use ScatterFeatureRequirement. 
https://www.commonwl.org/user_guide/23-scatter-workflow/index.html

**Comment by r06942072** [comment]
I apply the second way to implement it, and it works well.

![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/5be20ce0-2152-4db4-b874-9c1550934227)

![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/1cb38a74-6bab-4082-985d-b11cc10e9dfb)

![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/89820c8f-4de3-4599-acbf-b3ddca38679d)

**Comment by r06942072** [comment]
exclude to operate gunzip on md5checksums.txt

**Comment by r06942072** [comment]
I update outputs section of wget.cwl
```
outputs:
  out_wget_gz:
    type: File[]
    outputBinding:
      glob: '*.gz'

  out_wget_txt:
    type: File
    outputBinding:
      glob: '*.txt'
```

Therefore, the gunzip block is able to only capture **out_wget_gz** as input to avoid permanentfail.
